[project]
name = "wtr-qlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "invoke>=2.2.1",
    "loguru>=0.7.3",
    "rich>=14.2.0",
]





[tool.uv]
package = true

[dependency-groups]
dev = [
    "icecream>=2.1.8",
    "rich>=14.2.0",
]
