[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor="#60a5fa"
backgroundColor="#0b0d11"
secondaryBackgroundColor="#1a1f26"
textColor="#e2e8f0"
font="sans serif"
